---
Name: Aqua Security
Website: https://www.aquasec.com
Swag:
  - shirt
  - swag
  - stickers
Description: "1 Contribution: OSS superhero sticker pack, 3 Contributions: OSS superhero sticker pack and a special edition Aqua Hacktoberfest t-shirt, 5 Contributions: all of the above and the \"Kubernetes Security\" book, co-authored by Liz Rice, VP Open Source Engineering"
Details: https://blog.aquasec.com/aqua-open-source-security-hacktoberfest
