image: python:3.8

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: 10
  DOCKER_DRIVER: overlay2

before_script:
  - python -m venv venv
  - source venv/bin/activate

stages:
  - build
  - test
  - analyze
  - deploy

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - venv/
    - .sonar/cache

build:
  stage: build
  script:
    - pip install -U -e .
    - pip install wheel
    - python setup.py sdist bdist_wheel
  artifacts:
    name: tibia.py-dist
    paths:
      - dist/

sonarcloud-check:
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [ "" ]
  before_script:
    - git fetch --unshallow origin +refs/heads/*:refs/remotes/origin/*
  script:
    - sonar-scanner
  dependencies:
    - coverage
  only:
    - merge_requests
    - master
    - dev

docs:
  stage: build
  script:
    - pip install -U -e .[docs]
    - cd docs
    - make html
  artifacts:
    name: tibia.py-docs
    paths:
      - docs/_build/

coverage:
  stage: test
  script:
    - pip install -U -e .[test]
    - coverage run setup.py test
    - coverage report
    - coverage html
    - coverage xml
  artifacts:
    name: Coverage_Report
    paths:
      - htmlcov/
      - coverage.xml

pages:
  stage: deploy
  image: alpine
  cache: { }
  dependencies:
    - docs
    - coverage
  before_script: [ ]
  script:
    - mkdir public
    - mv htmlcov/ public/coverage/
    - mv docs/_build/html/* public/
  artifacts:
    paths:
      - public
  only:
    - master
    - dev
