---
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: (.*\.mbox)|(.*\.css)|(.*\.json)|(.*\.js)|(.*\.svg)|(.*/mails/.*-subject\.txt)
  - id: trailing-whitespace
    exclude: (.*\.mbox)|(.*\.svg)
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.7
  hooks:
  - id: remove-tabs
    exclude: (.*\.mbox)|(.*\.svg)|(.*\.sql)|(.*\.conf)
  - id: remove-crlf
    exclude: (.*\.mbox)|(.*\.svg)
