build: off

environment:

  matrix:

    - PYTHON: C:\Python35
    - PYTHON: C:\Python36
    - PYTHON: C:\Python37

init:
  - "ECHO %PYTHON%"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

test_script:
  - set PATH=%PYTHON%\\Scripts
  # Run py.test with 'v' (verbose) to show test function names and
  # 'rs' to show reasons for skipped tests
  - "pytest -v -rs"
