---
# This rule-set gets applied on each tag present in git.
# Rules are evaluated in the order they appear.
# - If a tag matches a black list rule, it's discarded and evaluation
# of rules for that tag stops.
# - If a tag matches a inclusion rule, it's added to the list of builds
#   to be done, and evaluation continues.

# Do not build old releases, we do not care about them, at least for now.
integration_rules:

- branch: master
  architecture: slc7_x86-64
  alidist: IB/v5-08/next
  alibuild: master
  package: thepeg-test

- branch: master
  architecture: slc7_x86-64
  alidist: IB/master/root6
  alibuild: master
  package: aliphysics
  defaults: root6

- branch: master
  architecture: osx_x86-64
  alidist: IB/master/root6
  alibuild: master
  package: aliphysics
  defaults: root6

- branch: master
  architecture: slc7_x86-64
  alidist: IB/v5-08/next
  alibuild: master
  package: aliroot-test
  defaults: coverage

- branch: master
  architecture: slc7_x86-64
  alidist: IB/v5-08/next
  alibuild: next
  package: aliroot-test

- branch: master
  architecture: slc6_x86-64
  alidist: IB/v5-08/next
  alibuild: next
  package: aliroot-test

- branch: master
  architecture: slc5_x86-64
  alidist: IB/v5-08/prod
  alibuild: master
  package: aliroot-test

- branch: master
  architecture: ubt14_x86-64
  alidist: IB/v5-08/next
  alibuild: next
  package: aliroot-test

- branch: master
  architecture: ubt1510_x86-64
  alidist: IB/v5-08/next
  alibuild: next
  package: aliroot-test

- branch: master
  architecture: osx_x86-64
  alidist: IB/v5-08/next
  alibuild: next
  package: aliroot-test

- branch: master
  architecture: slc7_x86-64
  alidist: IB/v5-08/next
  alibuild: next
  package: O2

- branch: master
  architecture: slc6_x86-64
  alidist: IB/v5-08/next
  alibuild: next
  package: O2

- branch: master
  architecture: ubt14_x86-64
  alidist: IB/v5-08/next
  alibuild: next
  package: O2

release_rules:
- 
  name: aliroot
  exclude: v[01234].*
- 
  name: aliroot
  exclude: ^[^v][^0-9].*
# More old releases, we also do not care.
- name: aliroot
  exclude: vAN
-
  name: aliroot
  exclude: v5-0[0-5].*
-
  name: aliroot
  exclude: v5-2.*
-
  name: aliroot
  exclude: v5-06-[01].*
-
  name: aliroot
  exclude: v5-06-2[0-5].*
-
  name: aliroot
  exclude: v5-06-.*(rc|test|itsmisalign).*
# Build recent releases for slc5, slc6
-
  name: aliroot
  include: v5-06.*
  alibuild: master
  alidist: IB/v5-06/prod
  architecture: slc5_x86-64
  env:
    TEST: all
-
  name: aliroot
  include: v5-06.*
  alibuild: master
  alidist: IB/v5-06/prod
  architecture: slc6_x86-64
  env:
    TEST: all
-
  name: aliroot
  include: v5-06.*
  alibuild: master
  alidist: IB/v5-06/prod
  architecture: slc7_x86-64
  env:
    TEST: all
-
  name: aliroot
  include: v5-05.*
  alibuild: master
  alidist: IB/v5-05/prod
  architecture: slc5_x86-64
  env:
    TEST: all
