---
- name: Install dev packages
  dnf:
    name:
    - gcc
    - python3
    - python3-devel
    - python3-alembic  # This pulls in python3-sqlalchemy
    # This breaks with Python 3 when installed from pip, it's terribly outdated.
    - python3-flask-xml-rpc
    - python3-psycopg2
    - redhat-rpm-config
    state: present

- name: Install python packages from requirements.txt
  pip:
    requirements: /vagrant/requirements.txt

- name: Create the database
  command: python3 createdb.py
  args:
    chdir: /vagrant/
    creates: /vagrant/alembic.ini
