package:
  name: quantities
  version: master

source:
  git_url: ../
  git_tag: master

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - numpy

test:
  imports:
    - quantities

about:
  license: BSD
  home: http://pythonhosted.org//quantities/
  summary: Physical quantities with units, based upon Numpy
