---
name: Tests

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run docker-compose tests
        run: docker-compose run --rm web tests
