---
name: Run CI checks

on: [pull_request]

jobs:
  unittests-fedora:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install required packages
        run: sudo apt-get install make flake8 pylint
      # it's not in Ubuntu 22.04, was added in 23.04
      - name: Install diff-cover from pip
        run: pip install diff-cover
      - name: Run the tests
        run: sudo make container-unittests-fedora
      - name: Run diff-cover
        run: diff-cover coverage.xml  --compare-branch=origin/$GITHUB_BASE_REF --fail-under=90
      - name: Run diff-quality (pylint)
        # we want to run this regardless of whether previous lint steps failed
        if: success() || failure()
        run: diff-quality --compare-branch=origin/$GITHUB_BASE_REF --violations=pylint --fail-under=90
      - name: Run diff-quality (flake8)
        # we want to run this regardless of whether previous lint steps failed
        if: success() || failure()
        run: diff-quality --compare-branch=origin/$GITHUB_BASE_REF --violations=flake8 --fail-under=90
  unittests-el7:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install make
        run: sudo apt-get install make
      - name: Run the tests
        run: sudo make container-unittests-el7
