name: tests
on: [push]

jobs:
  pep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install tox and flake8
        run: pip install tox flake8
      - name: Check syntax compliance
        run: tox -e pep8

  django:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        django: ["2.0", "2.1", "2.2", "3.0", "3.1"]
    steps:
      - uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install tox and django
        run: pip install tox "django==${{ matrix.django }}"
      - name: Run unit tests
        run: tox -e py-3.8-django-${{ matrix.django }}