name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install flake8 and Tox
        run: pip install flake8 tox
      - name: Lint with flake8
        run: |
          flake8 stacks --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 stacks --count --exit-zero --max-complexity=10
      - name: Run Tox
        run: tox -e py
  publish:
    needs: test
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Publish
        uses: pypa/gh-action-pypi-publish@main
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
