name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist:
          - py3_casacore_main
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Needed for `setuptools-scm`
          fetch-depth: 0

      - name: Build container
        run: docker build . -t ${{ matrix.dist }} -f .github/workflows/${{ matrix.dist }}.docker


