name: Run tests with tox

on: 
  push:
    branches:
      - main
      - develop
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .tox
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-test.txt') }}

      - name: Upgrade packaging tools
        run: python -m pip install --upgrade pip setuptools virtualenv wheel

      - name: Install dependencies
        run: python -m pip install --upgrade tox tox-py

      - name: Run tox targets for ${{ matrix.python-version }}
        run: tox --py current