name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  lint:
    name: Check lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          set -xeu
          python -VV
          pip install tox
      - name: Check lint
        run: tox -e check-lint

  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_DB: procrastinate
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
        ports:
          - 5432:5432

    strategy:
      matrix:
        include:
          - python-version: 3.9
            tox-env: py36-tests
          - python-version: 3.9
            tox-env: py37-tests
          - python-version: 3.9
            tox-env: py38-tests

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          set -xeu
          python -VV
          pip install tox coverage
      - name: Run tox targets for ${{ matrix.python-version }}
        run: tox -e ${{ matrix.tox-env }}
        env:
          PGDATABASE: procrastinate
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: password
          PYTEST_ADDOPTS: --cov-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  docs:
    name: Build doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          set -xeu
          python -VV
          pip install tox
      - name: Build doc
        run: tox -e docs

  deploy:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    needs:
      - lint
      - tests
      - docs
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          set -xeu
          python -VV
          pip install setuptools wheel
      - name: Build the wheel
        run: python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-actions-pypi-publish@main
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
