# This workflow will install Python dependencies, run tests and converage with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        python -m pip install -r requirements-dev.txt

    - name: 'Python2: Run tests'
      if: matrix.python-version == '2.7' || matrix.python-version == 'pypy2'
      run: |
        python sh.py travis
        python -m flake8 sh.py test.py

    - name: 'Python3: Run tests and report to Coveralls'
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: matrix.python-version != '2.7' && matrix.python-version != 'pypy2'
      run: |
        python sh.py travis
        python -m flake8 sh.py test.py
        python setup.py check --restructuredtext --metadata --strict
        python -m pip install coveralls==3.1.0
        coveralls --service=github
