name: tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: ["3.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Python dependencies
        run: |
          python -m pip install Markdown python-markdown-math pymdown-extensions
          python -m pip install docutils textile pygments codecov PyYAML
      - name: Install the project
        run: python setup.py install
      - name: Run tests
        run: coverage run -m unittest discover -s tests -v
      - name: Upload reports to Codecov
        if: ${{ matrix.python == 3.9 }}
        run: codecov
  pyflakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install pyflakes
        run: python -m pip install pyflakes
      - name: Run pyflakes
        run: python -m pyflakes markups/ tests/
